import { HumanMessage, SystemMessage } from "@langchain/core/messages";
import type { PromptAsset } from "../../../core/promptTypes";
import {
  createVolumeStrategyCritiqueSchema,
  createVolumeStrategySchema,
} from "../../../../services/novel/volume/volumeGenerationSchemas";
import {
  buildCommonNovelContext,
  buildCompactVolumeContext,
  buildStoryMacroContext,
  buildStrategyContext,
  type VolumeStrategyCritiquePromptInput,
  type VolumeStrategyPromptInput,
} from "./shared";

export function createVolumeStrategyPrompt(
  maxVolumeCount = 12,
): PromptAsset<
  VolumeStrategyPromptInput,
  ReturnType<typeof createVolumeStrategySchema>["_output"]
> {
  return {
    id: "novel.volume.strategy",
    version: "v1",
    taskType: "planner",
    mode: "structured",
    language: "zh",
    contextPolicy: {
      maxTokensBudget: 0,
    },
    outputSchema: createVolumeStrategySchema(maxVolumeCount),
    render: (input) => [
      new SystemMessage([
        "你是长篇网文总策划，负责先做“卷战略建议”，而不是直接生成最终卷纲。",
        "目标是帮助写作新手先决定：全书大概分几卷，前几卷哪些必须硬规划，后面哪些卷只能软规划。",
        "",
        "只输出严格 JSON，不要输出 Markdown、解释、注释、代码块或额外文本。",
        "",
        "返回且只能返回一个 JSON 对象，固定结构如下：",
        "{",
        '  "recommendedVolumeCount": 6,',
        '  "hardPlannedVolumeCount": 3,',
        '  "readerRewardLadder": "string",',
        '  "escalationLadder": "string",',
        '  "midpointShift": "string",',
        '  "notes": "string",',
        '  "volumes": [',
        "    {",
        '      "sortOrder": 1,',
        '      "planningMode": "hard",',
        '      "roleLabel": "string",',
        '      "coreReward": "string",',
        '      "escalationFocus": "string",',
        '      "uncertaintyLevel": "low"',
        "    }",
        "  ],",
        '  "uncertainties": [',
        "    {",
        '      "targetType": "volume",',
        '      "targetRef": "4",',
        '      "level": "medium",',
        '      "reason": "string"',
        "    }",
        "  ]",
        "}",
        "",
        "结构硬约束：",
        "1. 顶层必须且只能包含 recommendedVolumeCount、hardPlannedVolumeCount、readerRewardLadder、escalationLadder、midpointShift、notes、volumes、uncertainties。",
        `2. recommendedVolumeCount 必须是 1-${maxVolumeCount} 的正整数，且必须等于 volumes.length。`,
        "3. hardPlannedVolumeCount 必须是正整数，且不能大于 recommendedVolumeCount。",
        "4. volumes 必须按 sortOrder 从 1 开始连续递增，不允许跳号、重复或倒序。",
        "5. 前 hardPlannedVolumeCount 个 volume 的 planningMode 必须为 hard，剩余 volume 必须为 soft。",
        "6. uncertainties 只能写真实存在的不确定区域，不要为了凑字段硬写；没有明显风险时可返回空数组。",
        "",
        "字段语义：",
        "1. readerRewardLadder：整本书按卷推进时，读者每一阶段能获得什么不同类型的回报。",
        "2. escalationLadder：整本书的压迫源、代价或冲突是如何逐卷升级的。",
        "3. midpointShift：中盘阶段会发生什么性质变化，导致后续连载方向升级或转向。",
        "4. notes：给新手作者的明确规划建议，重点说明为什么这样分卷、为什么后半本不能过早锁死。",
        "5. roleLabel：该卷在整本书中的战略定位，例如开局立钩卷、反压起势卷、中盘转向卷。",
        "6. coreReward：该卷最核心的读者回报，必须具体，不能只写“剧情升级”。",
        "7. escalationFocus：该卷主要升级哪种压力、敌人、代价或局势。",
        "8. uncertaintyLevel：hard 卷通常为 low；soft 卷通常为 medium 或 high，除非输入已经非常稳定。",
        "9. uncertainties.targetRef：优先使用 book 或卷序号字符串，例如 4、5、6；不要引用不存在的对象。",
        "",
        "质量要求：",
        "1. 这是连载网文，不是出版式整书大纲。你要优先考虑追读动力和连载弹性。",
        "2. 不能一开始就把全书卷数和后半本细节锁死。",
        "3. 每卷的读者回报必须彼此区分，不能每卷都是“剧情升级”。",
        "4. 新手用户需要明确推荐，不要把关键决策都甩回给用户。",
        "5. 如果信息不足，优先给出保守、可执行、便于后续扩展的规划；不要编造后半本的具体大反转来假装完整。",
        "6. 除非输入已经非常明确，否则默认前 2-3 卷为硬规划，后续卷保持软规划弹性。",
      ].join("\n")),
      new HumanMessage([
        "工作模式：卷战略建议",
        buildCommonNovelContext(input.novel),
        `建议卷数起点：${input.suggestedVolumeCount}`,
        `当前卷骨架：${buildCompactVolumeContext(input.workspace.volumes)}`,
        buildStoryMacroContext(input.storyMacroPlan),
        input.guidance?.trim() ? `额外指令：${input.guidance.trim()}` : "",
      ].filter(Boolean).join("\n\n")),
    ],
  };
}

export const volumeStrategyCritiquePrompt: PromptAsset<
  VolumeStrategyCritiquePromptInput,
  ReturnType<typeof createVolumeStrategyCritiqueSchema>["_output"]
> = {
  id: "novel.volume.strategy.critique",
  version: "v1",
  taskType: "review",
  mode: "structured",
  language: "zh",
  contextPolicy: {
    maxTokensBudget: 0,
  },
  outputSchema: createVolumeStrategyCritiqueSchema(),
  render: (input) => [
    new SystemMessage([
      "你是连载网文结构审稿人，负责审查“卷战略建议”是否真的适合连载推进。",
      "你不是修 JSON，而是指出卷战略是否存在结构风险。",
      "",
      "只输出严格 JSON，不要输出 Markdown、解释、注释、代码块或额外文本。",
      "",
      "审查重点：",
      "1. 是否过早把后半本硬规划。",
      "2. 前几卷读者回报是否同质化。",
      "3. 升级梯度是否会导致中段塌陷。",
      "4. 中盘转向是否不清楚。",
      "5. 是否缺少明确的不确定性声明。",
      "",
      "返回且只能返回一个 JSON 对象，固定结构为：",
      "{",
      '  "overallRisk": "low | medium | high",',
      '  "summary": "string",',
      '  "issues": [',
      "    {",
      '      "targetRef": "book | volume:3 | volumes:4-5",',
      '      "severity": "low | medium | high",',
      '      "title": "string",',
      '      "detail": "string"',
      "    }",
      "  ],",
      '  "recommendedActions": ["string"]',
      "}",
      "issues 中每条都要写清 targetRef、severity、title、detail，不能只写抽象评价。",
      "如果没有明显问题，issues 可为空数组，但 summary 仍要明确说明风险为什么低。",
    ].join("\n")),
    new HumanMessage([
      "工作模式：卷战略审稿",
      buildCommonNovelContext(input.novel),
      buildStrategyContext(input.strategyPlan),
      `当前卷骨架：${buildCompactVolumeContext(input.workspace.volumes)}`,
      buildStoryMacroContext(input.storyMacroPlan),
      input.guidance?.trim() ? `额外指令：${input.guidance.trim()}` : "",
    ].filter(Boolean).join("\n\n")),
  ],
};
