export interface BackgroundM4bSettleRetryContext {
  attempt: number;
  delayMs: number;
}

/**
 * Retries only the small database projection that publishes a completed m4b
 * result. The encoded file is never regenerated by this queue.
 *
 * A single latest operation is retained per task. Generation-token CAS remains
 * the authority inside the operation, so a retry from an older generation
 * becomes a harmless no-op after reprocess/redo rotates the token.
 */
export class BackgroundM4bSettleRetry {
  private readonly timers = new Map<string, NodeJS.Timeout>();

  private readonly latestTokens = new Map<string, symbol>();

  constructor(
    private readonly initialDelayMs = 100,
    private readonly maxDelayMs = 30_000,
  ) {}

  async persist(
    taskId: string,
    operation: () => Promise<void>,
    onRetry: (error: unknown, context: BackgroundM4bSettleRetryContext) => void,
  ): Promise<void> {
    this.cancelTimer(taskId);
    const token = Symbol(taskId);
    this.latestTokens.set(taskId, token);
    try {
      await operation();
      if (this.latestTokens.get(taskId) === token) {
        this.latestTokens.delete(taskId);
      }
    } catch (error) {
      if (this.latestTokens.get(taskId) === token) {
        this.schedule(taskId, token, operation, onRetry, 1, error);
      }
    }
  }

  stop(): void {
    for (const timer of this.timers.values()) clearTimeout(timer);
    this.timers.clear();
    this.latestTokens.clear();
  }

  private schedule(
    taskId: string,
    token: symbol,
    operation: () => Promise<void>,
    onRetry: (error: unknown, context: BackgroundM4bSettleRetryContext) => void,
    attempt: number,
    error: unknown,
  ): void {
    const delayMs = Math.min(
      this.maxDelayMs,
      this.initialDelayMs * (2 ** Math.min(20, Math.max(0, attempt - 1))),
    );
    onRetry(error, { attempt, delayMs });
    const timer = setTimeout(() => {
      if (
        this.latestTokens.get(taskId) !== token
        || this.timers.get(taskId) !== timer
      ) return;
      this.timers.delete(taskId);
      void operation().then(() => {
        if (this.latestTokens.get(taskId) === token) {
          this.latestTokens.delete(taskId);
        }
      }).catch((retryError) => {
        if (this.latestTokens.get(taskId) !== token) return;
        this.schedule(taskId, token, operation, onRetry, attempt + 1, retryError);
      });
    }, delayMs);
    timer.unref?.();
    this.timers.set(taskId, timer);
  }

  private cancelTimer(taskId: string): void {
    const timer = this.timers.get(taskId);
    if (timer) clearTimeout(timer);
    this.timers.delete(taskId);
  }
}
